framework:
      redis:
        enable: true
        redis-mode: single
        master: 10.130.36.104:6379
        connection-timeout: 500
        so-timeout: 1000
        db: 0
        max-total: 18
        min-idle: 0
